### ISSUE TITLE
Issue #1: User can get a randomized quote or dad joke

### ISSUE THREAD

**Issue by ejgilleland** [ejgilleland/ajax-project#1]
## Functionality: 
On the main page, the user can get a button that will randomly retrieve either a random quote or a dad joke — will you be inspired or get a dad joke?

## Plan:
Design the page and add base functionality (retrieve a joke or quote from one of two APIs)

## Task List:

- [x] Build the page's basic structure in HTML
- [x] Add styling to match the wireframe
   - [x] Fonts
   - [x] Colors
   - [x] Positioning
   - [x] Breakpoints
- [x] Create user data model/object in JS
- [x] Add event listener to document
   - [x] If user clicks on roulette image, create an XMLHttpRequest() object
   - [x] Get either a dad joke from https://icanhazdadjoke.com/ API or a quote from https://github.com/lukePeavey/quotable API
      - [x] Build functionality to return a quote from https://github.com/lukePeavey/quotable
      - [x] Add the quote's contents to the page
      - [x] Build functionality to return a joke from https://icanhazdadjoke.com/
      - [x] Add the joke's contents to the page
      - [x] Add randomization to the XMLHttpRequest
      - [x] Ensure that the XMLHttpRequest is properly handled, based on which API was utilized (ie, if different property names are used in the response object).
   - [x] (1st click on new page) un-hide the joke/quote container that is built into the html, get the contents (either quote or joke) from the XMLHttpRequest.response
   - [x] (2nd click and after) Update the contents of the joke/quote container (no need to un-hide container)
- [x] Add spinning animation to the roulette image while retrieving a quote or joke
