### ISSUE TITLE
Issue #2: User can like the quote or dad joke

### ISSUE THREAD

**Issue by ejgilleland** [ejgilleland/ajax-project#2]
## Functionality:
After the quote is retrieved, the user can click an icon to like the displayed joke or quote

## Plan:
Add Event Listener to heart icon and update user data when heart is clicked, also update icon to be solid.

## Task List:

- [x] Add an event listener on the .reactions container (this container includes the thumbs down and the heart font awesome icons)
- [x] If `event.target === page.$emptyHeart`:
   - [x] Add an object to `data.js`'s `user.likes` array, which contains two properties: 
      - [x] `joke`: a `boolean`, used to indicate if the item came from https://icanhazdadjoke.com/ or https://api.quotable.io/random
      - [x] `id`: a `string`, used to reference the id of the liked item
   - [x] use `classList.add('hidden')` to hide the `.empty-heart` icon
   - [x] use `classList.remove('hidden')` to show the `.full-heart` icon
- [x] Check if a quote/joke that is retrieved is already in `user.likes` when retrieved from the API (check if `xhr.response.id === user.likes[i].favorites.id`)
   - [x] display the `.full-heart` icon when the quote/joke loads
- [x]  add `beforeunload` event listener to the `window` to save `user` to `localStorage`
- [x] add functionality to retrieve `user` data from `localStorage` when page is loaded
