### ISSUE TITLE
Issue #3: User can dislike the quote or dad joke

### ISSUE THREAD

**Issue by ejgilleland** [ejgilleland/ajax-project#3]
## Functionality:
After the quote is retrieved, the user can click an icon to dislike the displayed joke or quote

## Plan:
Add Event Listener to thumbsdown icon and update user data when the icon is clicked.
- If item is already liked, remove liked item from user data and update heart icon.
- If item is already disliked and heart is clicked, remove disliked item from user data and update thumbsdown icon.

## Task List:

- [x] Modify the `click` event listener on the `.reactions` container: check if `event.target === page.$emptyThumb`
- [x] Add an object to `data.js`'s `user.dislikes` array, which contains two properties: 
   - [x] `joke`: a `boolean`, used to indicate if the item came from https://icanhazdadjoke.com/ or https://api.quotable.io/random
   - [x] `id`: a `string`, used to reference the id of the liked item
- [x] use `classList.add('hidden')` to hide the `.empty-thumb` icon
- [x] use `classList.remove('hidden')` to show the `.full-thumb` icon
- [x] Check if a quote/joke that is retrieved is already in `user.dislikes` when retrieved from the API (check if `xhr.response.id === user.dislikes[i].id`)
   - [x] display the `.full-thumb` icon when the quote/joke loads
 - [x] If a quote/joke is in `user.likes` and the thumbs down icon is clicked to dislike the displayed item:
   - [x] Remove the item from `user.likes`
   - [x] use `classList.add('hidden')` to hide the `.full-heart` icon
   - [x] use `classList.remove('hidden')` to show the `.empty-heart` icon
 - [x] If a quote/joke is in `user.dislikes` and the thumbs down icon is clicked to like the displayed item:
   - [x] Remove the item from `user.dislikes`
   - [x] use `classList.add('hidden')` to hide the `.full-thumb` icon
   - [x] use `classList.remove('hidden')` to show the `.empty-thumb` icon
