### ISSUE TITLE
Issue #4: User can remove liked/disliked items

### ISSUE THREAD

**Issue by ejgilleland** [ejgilleland/ajax-project#4]
## Functionality:
The user's preferences may change, so they can remove things that they no longer like or dislike!

## Plan:
Add Event Listener to thumbsdown and heart icons.
If they are solid (implying the item is liked or disliked), the quote/joke is removed from the user's likes/dislikes data, and the icon is updated to no longer be solid.

## Task List:

- [x] Modify the `click` event listener on the `.reactions` container: check if `event.target === page.$fullHeart`
   - [x] Remove the quote/joke from `user.likes` by using `appData.idRemover(user.likes)`
   - [x] use `classList.add('hidden')` to hide the `.full-heart` icon
   - [x] use `classList.remove('hidden')` to show the `.empty-heart` icon
- [x] Modify the `click` event listener on the `.reactions` container: check if `event.target === page.$fullThumb`
   - [x] Remove the quote/joke from `user.dislikes` by using `appData.idRemover(user.dislikes)`
   - [x] use `classList.add('hidden')` to hide the `.full-thumb` icon
   - [x] use `classList.remove('hidden')` to show the `.empty-thumb` icon
