### ISSUE TITLE
Issue #5: User can view their likes

### ISSUE THREAD

**Issue by ejgilleland** [ejgilleland/ajax-project#5]
## Functionality:
User can view their liked items by clicking a link in the navbar

## Plan:
Add event listener to "Likes" link in navbar, change view using Javascript to show a list of all liked items.
If a heart icon is clicked while viewing liked items, the item is removed from the user's data and dynamically removed from the "Likes" list view.

## Task List:

- [x] create a new html container to house all liked items
- [x] style the container to match wireframe (use dummy joke/quote containers for the time being)
- [x] add a `data-view` attribute to the main container and the "likes" container, and the "Home" and "Likes" link
- [x] hide the 'Likes' container by default
- [x] add an event listener to the home/likes links (on desktop view)
- [x] in the event listener callback, update the `classList` to show the container that was selected and hide the container that was not selected (use the matching `data-view` attribute/dataset property between the link and the container)
- [x] on mobile view, if the bars icon is clicked:
   - [x] Make a modal dropdown appear underneath the bars icon, with links to "Home" and "Likes"
   - [x] Style the dropdown:
      - [x] Positioning of dropdown
      - [x] Font/colors
      - [x] Positioning of content
   - [x] if the area outside of the modal is clicked, hide the modal
   - [x] if the bars icon is clicked again, hide the modal
   - [x] if a link is clicked, hide the modal and swap to the relevant view using the previously defined view swapper
- [x] Update the `user.likes` data to contain the body of the quote/joke (to avoid doing `GET` requests to render the "Likes" page)
- [x] Render the "Likes" page using the `likes` array in the `user` data
   - [x] Create a method on the appData variable that returns a DOM tree for a joke/quote container
   - [x] Populate the DOM elements and append the DOM tree to the "Likes" page when a quote/joke is added to `user.likes`
   - [x] Listen for the `DOMContentLoaded` event:
      - [x] If the `user.likes` array is empty, make the default `likes` page message appear
      - [x] If the `user.likes` array is not empty, render all currently existing liked items on the Likes page using the `likesRenderer` method
- [x] In the "Likes" page:
   - [x]  if the heart icon is clicked, remove the item (quote/joke) from the view and remove the item from `user.likes`
   - [x] if the thumbsdown icon is clicked, remove the item from the view, and remove item from `user.likes` & add to `user.dislikes`
- [x] On the main page, if the currently-displayed joke/quote is currently in `user.likes` (and thus contained on the "Likes" page):
   - [x] If the `heart` icon is clicked, remove the liked item from the "Likes" page:
      - [x] use `document.queryselector()` to select the node with a `data-id` attribute that matches `appdata.currentResponseID` and `element.remove()` to remove it
   - [x] If the `thumbsdown` is clicked, remove the liked item from the "Likes" page:
      - [x] use `document.queryselector()` to select the node with a `data-id` attribute that matches `appdata.currentResponseID` and `element.remove()` to remove it
